name: E2E Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        # Configure npm to use the token for private packages
        registry-url: 'https://registry.npmjs.org'

    - name: Configure npm for private packages
      run: |
        # Create .npmrc file with authentication token
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Start servers in background
      run: |
        # Start the Express server
        npm run server &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        
        # Start the React dev server
        npm run start:no-open &
        CLIENT_PID=$!
        echo "CLIENT_PID=$CLIENT_PID" >> $GITHUB_ENV
        
        # Wait for servers to be ready
        echo "Waiting for servers to start..."
        npx wait-on http://localhost:3001/api/health http://localhost:3000 --timeout 60000

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-videos
        path: test-results/
        retention-days: 30

    - name: Cleanup processes
      if: always()
      run: |
        # Kill the background processes
        if [ ! -z "$SERVER_PID" ]; then
          kill $SERVER_PID || true
        fi
        if [ ! -z "$CLIENT_PID" ]; then
          kill $CLIENT_PID || true
        fi
        # Kill any remaining processes on the ports
        pkill -f "node.*server" || true
        pkill -f "webpack.*serve" || true 