name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Test without authentication
      run: |
        echo "=== Testing package access without auth ==="
        npm view @backline.js/alert-panel || echo "Package not accessible"
        
    - name: Configure npm authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc
        echo "=== .npmrc contents ==="
        cat .npmrc
        echo "=== Testing package access with auth ==="
        npm view @backline.js/alert-panel || echo "Package not accessible"
        
    - name: Install dependencies
      run: |
        echo "=== npm config before install ==="
        npm config list
        echo "=== .npmrc contents before install ==="
        cat .npmrc
        echo "=== Starting npm install ==="
        npm install --verbose

    - name: Run unit tests
      run: npm test

    - name: Run unit tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30 