name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Configure npm for private packages
      run: |
        # Clear any existing npm configuration
        npm config delete registry
        npm config delete _authToken
        
        # Create .npmrc file with authentication token
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc
        echo "auth-type=legacy" >> .npmrc
        
        # Verify .npmrc was created (without showing token)
        echo "Created .npmrc file:"
        cat .npmrc | sed 's/:_authToken=.*/:_authToken=***HIDDEN***/'
        
        # Show npm config to verify
        echo "NPM config:"
        npm config list

    - name: Install dependencies
      run: |
        # Try npm ci with explicit registry and auth
        npm ci --registry=https://registry.npmjs.org/ --auth-type=legacy

    - name: Run unit tests
      run: npm test

    - name: Run unit tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30 